agentName: agentaip003
envName: dev
agentRuntimeName: agentaip003_dev
imageRepo: 229560443702.dkr.ecr.us-west-2.amazonaws.com
tag: latest
roleArn: arn:aws:iam::229560443702:role/service-role/AmazonBedrockAgentCoreRuntimeDefaultServiceRole

environmentVariables:
  TENANT_SECRETS_PATH: "tenant01/agent001_dev"
  # REGION: "us-west-2"
